### ISSUE TITLE
support requirement files

### ISSUE THREAD

**Issue by houbie** [pyprojectx/pyprojectx#104]
uv supports requirements.txt files, pyproject.toml files and combinations with multiple `-r` supplied to `pip install`.
uv requires them to be provided separately, so we need special logic to separate them from plain text requirements.

example configuration:
```toml
[tool.pyprojectx.venv]
requirements = [
    "-r pyproject.toml",
    "-r dev-requirements.txt",
    "some-package==1.2.3"
]
```
