### ISSUE TITLE
add prerelease configuration

### ISSUE THREAD

**Issue by houbie** [pyprojectx/pyprojectx#105]
Add a prerelease configuration property that is passed on to uv when installing dependencies:

```toml
[tool.pyprojectx]
prerelease = "allow"
```
