### ISSUE TITLE
lockfile is still tied to python version

### ISSUE THREAD

**Issue by DetachHead** [pyprojectx/pyprojectx#110]
**Describe the bug**
i'm not sure if it's an issue with pyprojectx or uv, but i'm noticing a different lockfile being generated on python 3.10 and 3.12.

**To Reproduce**
1. install python 3.12
2. add pdm to your project:
    ```toml
    [tool.pyprojectx]
    main = ["pdm>=2.16.1"]
    ```
3. run `./pw --lock`, which generates the following lockfile:
    ```toml
    [main]
    requirements = ["anyio==4.4.0", "blinker==1.8.2", "certifi==2024.7.4", "dep-logic==0.4.1", "distlib==0.3.8", "filelock==3.15.4", "findpython==0.6.1", "h11==0.14.0", "hishel==0.0.29", "httpcore==1.0.5", "httpx==0.27.0", "idna==3.7", "installer==0.7.0", "markdown-it-py==3.0.0", "mdurl==0.1.2", "msgpack==1.0.8", "packaging==24.1", "pbs-installer==2024.4.24", "pdm==2.16.1", "platformdirs==4.2.2", "pygments==2.18.0", "pyproject-hooks==1.1.0", "python-dotenv==1.0.1", "resolvelib==1.0.1", "rich==13.7.1", "shellingham==1.5.4", "sniffio==1.3.1", "socksio==1.0.0", "tomlkit==0.12.5", "truststore==0.9.1 ; python_version >= '3.10'", "typing-extensions==4.12.2", "unearth==0.16.0", "virtualenv==20.26.3"]
    hash = "228424c509dec4543c5c7b8f68f4e875"
    ```
4. uninstall python 3.12, then install python 3.10
5. run `./pw --lock` again, which generates the following lockfile:
    ```toml
    [main]
    requirements = ["anyio==4.4.0", "blinker==1.8.2", "certifi==2024.7.4", "dep-logic==0.4.1", "distlib==0.3.8", "exceptiongroup==1.2.1 ; python_version < '3.11'", "filelock==3.15.4", "findpython==0.6.1", "h11==0.14.0", "hishel==0.0.29", "httpcore==1.0.5", "httpx==0.27.0", "idna==3.7", "installer==0.7.0", "markdown-it-py==3.0.0", "mdurl==0.1.2", "msgpack==1.0.8", "packaging==24.1", "pbs-installer==2024.4.24", "pdm==2.16.1", "platformdirs==4.2.2", "pygments==2.18.0", "pyproject-hooks==1.1.0", "python-dotenv==1.0.1", "resolvelib==1.0.1", "rich==13.7.1", "shellingham==1.5.4", "sniffio==1.3.1", "socksio==1.0.0", "tomli==2.0.1 ; python_version < '3.11'", "tomlkit==0.12.5", "truststore==0.9.1 ; python_version >= '3.10'", "typing-extensions==4.12.2", "unearth==0.16.0", "virtualenv==20.26.3"]
    hash = "228424c509dec4543c5c7b8f68f4e875"
    ```
the difference being that the additional `"exceptiongroup==1.2.1 ; python_version < '3.11'"` and `"tomli==2.0.1 ; python_version < '3.11'"` dependencies were added to the lockfile generated on python 3.10

**Expected behavior**
same lockfile is generated on both versions

**Desktop (please complete the following information):**
 - Python  version: 3.10 and 3.11
 - OS: windows 10 and ubuntu

**Additional context**
the original issue (#85) was closed but it seems that the issue is still present in pyprojectx 3.0.2
