### ISSUE TITLE
(🎁) add a way to update `px`/`pxg`

### ISSUE THREAD

**Issue by KotlinIsland** [pyprojectx/pyprojectx#119]
when i need to update `px`/`pxg` the steps really clunky

```
> pxg download-pw
> px --install-px --force-install
```

i think a default alias in pxg would be great for this this:
```toml
[tool.pyprojectx.aliases]
self-update = { cmd = "pxg download-pw; .\\pw --install-px --force-install", shell = "powershell" }
```

the part about running `download-pw` in the current directory is really sus though, maybe there is a better solution

additionally, `.\pw --install-px --force-install` will completely reset your `pxg` configuration to default, so this proposed solution is non-viable
