### ISSUE TITLE
(🎁) make `scripts_dir` work with a venv

### ISSUE THREAD

**Issue by KotlinIsland** [pyprojectx/pyprojectx#126]
i want to go:
```py
> px do_thing
```
but it fails because `do_thing.py` has dependencies (managed by `uv`)

even if i have my venv activated, the script still fails, maybe `px` is isolating it or something

i'm sure you can invent some awesome solution here, my suggestion would be something along the lines of:
```toml
[tool.pyprojectx]
main = ["uv"]
scripts_dir = "scripts"
scripts_environment = ".venv"
```
