### ISSUE TITLE
creating an alias for a script with the same name gives errors

### ISSUE THREAD

**Issue by houbie** [pyprojectx/pyprojectx#131]
Defining an alias with exactly the same name as a script, always results in an _is ambiguous_ error when ran.

Solution: give the alias a higher priority to make it possible to call the script from the alias.
F.e, alias _bin/my-script_
```toml
[tool.pyprojectx.aliases]
my-script = "uv run bin/my-script"
```
