### ISSUE TITLE
the version of uv used by pyprojectx should not use the project's `requires-python` version

### ISSUE THREAD

**Issue by DetachHead** [pyprojectx/pyprojectx#137]
**Describe the bug**
see #136 & #120, currently the version of uv used by pyprojectx (currently 0.5.2) needs to be updated every time a new python version is released if my project itself uses uv to manage its dependencies / python installation.

**To Reproduce**
1. set `requires-python = ">=3.13.1, <3.14"` in `pyproject.toml` for a project that has uv as a pyprojectx dependency:
    ```toml
    [project]
    requires-python = ">=3.13.1, <3.14"
   
    [tool.pyprojectx]
    main = ["uv==0.5.20"]
    ```
2. run any pyprojectx command, eg. `./pw uv sync`

**Expected behavior**
i think the version of uv used by pyprojectx should just ignore the `requires-python` in `pyproject.toml`, since this version of uv is only used internally by pyprojectx to install the dependencies specified in the `[tool.pyprojectx]` section.

only the version of uv specified in `[tool.pyprojectx]` (0.5.2) should respect `requires-python`, because that's the version of uv my project actually uses.
