### ISSUE TITLE
(🐞) Compound aliases don't work on windows with spaces in project path

### ISSUE THREAD

**Issue by KotlinIsland** [pyprojectx/pyprojectx#26]
```toml
[tool.pyprojectx.aliases]
a = "echo a"
b = "echo b"
c = ["pw@ a", "pw@ b"]
```
```
~\a b > px a
a
~\a b > px b
b
~\a b > px c
'C:\Users\AMONGUS\a' is not recognized as an internal or external command,
operable program or batch file.
```
