### ISSUE TITLE
(🎁) Set alias interpreter explicitly

### ISSUE THREAD

**Issue by KotlinIsland** [pyprojectx/pyprojectx#27]
I don't want the execution of my aliases to be affected by user settings, I would like them to be reproducible.

Maybe aliases should be definable per shell.
```toml
[tool.pyprojectx.shell.pwsh.aliases]
clean = "Remove-Item -Recurse build"
```

Or if not per shell, then being able to set it at the os level:
```toml
[tool.pyprojectx.os.win]
alias-interpreter = "pwsh.exe"
```

Additionally, I don't want to write aliases in bat, I would prefer pwsh.

**Comment by houbie** [comment]
Something like this? 
```
subprocess.run([shell, "-c", full_alias_command])
```

And then configure it per alias:
```toml
[tool.pyprojectx.aliases]
clean = { cmd: "Remove-Item -Recurse build", shell = "pwsh.exe" }
```
or by default:
```toml
[tool.pyprojectx.os.win]
shell = "pwsh.exe"
```
