### ISSUE TITLE
Allow passing environment variables to commands and aliases

### ISSUE THREAD

**Issue by scott-8** [pyprojectx/pyprojectx#37]
Really love your project! One thing that would be nice to be able to pass environment variables to the different commands aliases, like [PDM scripts](https://pdm.fming.dev/latest/usage/scripts/#script-options). 

For example, PDM allows you to set PDM_IGNORE_ACTIVE_VENV. This feature is only available via an environment variable. It would be useful to be able to set variables like this:

```
[tool.pyprojectx]
pdm = "pdm==2.10.0"
pdm.env = { PDM_IGNORE_ACTIVE_VENV= "true" }
```

or

```
[tool.pyprojectx.aliases]
lock = "pdm lock --refresh"
lock.env = { PDM_LOCKFILE = "file.lock" }
```

**Comment by houbie** [comment]
solved this by allowing default env variables (always added) and per-alias env variables:

```toml
[tool.pyprojectx]
env = { ENV_VAR1="ENV_VAR1"}
[tool.pyprojectx.aliases]
alias = { cmd = 'echo "$ENV_VAR1 $ENV_VAR2"', env = { ENV_VAR2="ENV_VAR2"}}
```
