### ISSUE TITLE
allow to specify the working directory for commands

### ISSUE THREAD

**Issue by houbie** [pyprojectx/pyprojectx#46]
```toml
[tool.pyprojectx]
cwd = "PROJECT_DIR" # default for all commands

[tool.pyprojectx.aliases]
start-ui= { cwd = "ui", cmd= "npm start" }
ls= { cwd= ".",  cmd= "ls" }
```
