### ISSUE TITLE
executing a tool directly (without alias) assumes that the extension is always .exe on windows

### ISSUE THREAD

**Issue by houbie** [pyprojectx/pyprojectx#48]
Given the following scenario:
```toml
[tool.pyprojectx]
my-tool = "some-requirement"
```
and a script `my-tool.bat` that you want to execute within the tool's virtual env

Running `./pw my-tool` currently will try to execute _path/to/venv-scripts/my-tool.exe_
