### ISSUE TITLE
make it easier to group tools in one virtual environment

### ISSUE THREAD

**Issue by houbie** [pyprojectx/pyprojectx#50]
Pyprojectx started with the idea that you should be able to install python tools in isolation, but that goes further than the actual goal: create reproducible development setups that don't impact your project's dependencies.

So it is ok to install all or most of your build tools together if that setup works for your project.

### Proposed solution
Give special meaning to the **main** tool venv and use that one by default.

```toml
[tool.pyprojectx]
main.requirements = [
    "pdm==2.10.3",
    "ruff==0.1.4",
    "pre-commit==3.5.0",
]
main.post-install = "pre-commit install"

[tool.pyprojectx.aliases]
install = "pdm install"
fix = "ruff src tests --fix"
```

Everything runs in the main context if not specified otherwise and if the first command is not equal to the name of another context

### Side note on the naming
#42 introduced `tool` for aliases. When installing multiple tools together, `context` will be a better name
