### ISSUE TITLE
(🎁) `px` should have an `init` command that adds the `pw` script to the current folder

### ISSUE THREAD

**Issue by KotlinIsland** [pyprojectx/pyprojectx#59]
When I want to create a new project I have to lookup and run the command to download `pw`, but I already have `px` installed, it should be able to initialize a project.

**Comment by houbie** [comment]
Going for a simple solution that prevents file locking issues when trying to replace the pw scripts that are executing.
So instead of adding an `--init` option, I'll add a `download-pw` alias to the default global ~/.pyprojectx/global/pyproject.toml:

```toml
[tool.pyprojectx.aliases]
# linux
download-pw = "curl -LO https://github.com/pyprojectx/pyprojectx/releases/latest/download/wrappers.zip && unzip -o wrappers.zip && rm -f wrappers.zip"

# windows
download-pw = { cmd = "Invoke-WebRequest https://github.com/pyprojectx/pyprojectx/releases/latest/download/wrappers.zip -OutFile wrappers.zip; Expand-Archive -Force -Path wrappers.zip -DestinationPath .; Remove-Item -Path wrappers.zip", shell = "powershell" }
```
Then you can just `pxg download-pw` or even `pxg dP`
