### ISSUE TITLE
locking loops forever when the post-install action is an alias

### ISSUE THREAD

**Issue by houbie** [pyprojectx/pyprojectx#75]
following config will cause `./pw --lock` to run forever

```toml
[tool.pyprojectx.main]
requirements = [
    "pre-commit",
]
post-install = "@pre-commit-install"

[tool.pyprojectx.aliases]
pre-commit-install= "pre-commit install"
```
