### ISSUE TITLE
add support to create a project virtual environment

### ISSUE THREAD

**Issue by houbie** [pyprojectx/pyprojectx#80]
Create a virtual environment that can be activated and used for project development.
This can be achieved by allowing to specify the installation directory for a tool context:

```toml
[tool.pyprojectx.venv]
dir = "@PROJECT_DIR/.venv"
requirements = ["pytest==8.0.0", "-e ."]

[tool.pyprojectx.aliases]
test = { cmd = "pytest", ctx = "venv" }
```
