### ISSUE TITLE
lockfile doesn't seem to work

### ISSUE THREAD

**Issue by DetachHead** [pyprojectx/pyprojectx#84]
**Describe the bug**
the `pw.lock` file doesn't seem to work, because it gets regenerated automatically when a new version of a dependency is available, which defeats the purpose

**To Reproduce**
1. have a dependency specified to a version older than the latest release:
    ```toml
    # pyproject.toml
    [tool.pyprojectx]
    pdm = "pdm>=2.12.2"
    ```
   and a lockfile where it's pinned to that outdated version:
    ```toml
    # pw.lock
    [pdm]
    requirements = ["CacheControl==0.13.1", "Pygments==2.17.2", "blinker==1.7.0", "certifi==2023.11.17", "charset-normalizer==3.3.2", "dep-logic==0.0.4", "distlib==0.3.8", "filelock==3.13.1", "findpython==0.4.1", "idna==3.6", "installer==0.7.0", "markdown-it-py==3.0.0", "mdurl==0.1.2", "msgpack==1.0.7", "packaging==23.2", "pdm==2.12.2", "platformdirs==4.1.0", "pyproject_hooks==1.0.0", "python-dotenv==1.0.1", "requests-toolbelt==1.0.0", "requests==2.31.0", "resolvelib==1.0.1", "rich==13.7.0", "shellingham==1.5.4", "tomlkit==0.12.3", "truststore==0.8.0", "unearth==0.14.0", "urllib3==2.1.0", "virtualenv==20.25.0"]
    hash = "51e180b34ec54ec0103a5b9e087eaf00"
    ```
2. run `./pw pdm --version`

**Expected behavior**
the version from the lockfile is installed if it's not already, then it prints `PDM, version 2.12.2`

**Actual behavior**
the latest version within the range is downloaded, and the lockfile is updated automatically to match. it then prints `PDM, version 2.12.3`

**Desktop (please complete the following information):**
 - Python  version: 3.12
 - OS: windows 10

**Additional context**
there probably needs to be a separate command to update the lockfile, like what pdm and poetry does (`pdm install` to install dependencies from the lockfile and `pdm update` to update the lockfile with the latest versions)
